/* =====================================================================
   KITCHEN GARAGE — site data  (real menu, transcribed from KG Menu PDF)
   ---------------------------------------------------------------------
   Edit menu / prices / info here only. Prices in USD ($).
   `opt`  = small note shown next to the price (size / tossed / large…)
   Badges: popular, spicy, veg, isNew
   ===================================================================== */

window.KG_DATA = {
  currency: "$",
  deliveryFee: 3,
  freeDeliveryOver: 30,
  minOrder: 8,

  restaurant: {
    name: "Kitchen Garage",
    tagline: "Charcoal-grilled burgers, hand-breaded wings & more.",
    blurb:
      "Aley's home for Black Angus smash burgers, hand-breaded wings in 15 flavors, loaded fries and The Noms coffee bar. Eat in, take away, or get it delivered — and yes, we accept crypto.",
    phone: "+961 81 412 522",
    whatsapp: "+96181412522",
    email: "hello@kitchengarage.lb",
    address: "Bkheshtay Street, Aley, Lebanon",
    area: "Aley",
    mapEmbed: "https://www.google.com/maps?q=Kitchen+Garage+Aley+Bkheshtay+Lebanon&output=embed",
    mapsDirections: "https://www.google.com/maps/dir/?api=1&destination=Kitchen+Garage+Aley+Lebanon",
    googleReviews: "https://www.google.com/maps/search/?api=1&query=Kitchen+Garage+Aley+Lebanon",
    instagram: "https://www.instagram.com/kitchengaragelb/",
    facebook: "https://www.facebook.com/kitchengaragelb/",
    rating: 4.8,
    reviewCount: 280,
    acceptsCrypto: true,
    hours: [
      { d: "Monday – Sunday", h: "2:00 PM – 10:00 PM" },
      { d: "Service", h: "Dine-in · Takeaway · Delivery" },
    ],
  },

  reviews: [
    { name: "Rami H.", stars: 5, text: "The Carnivores burger is a monster — charcoal flavor is unreal. Wings come in every flavor you can imagine." },
    { name: "Lara K.", stars: 5, text: "Ordered delivery to Aley, arrived hot and fast. The Noms iced Spanish latte is my new addiction." },
    { name: "Karim D.", stars: 4, text: "Loaded fries and the KG Mix are perfect for sharing. Cool spot, great music, friendly staff." },
  ],

  // Hero imagery (real photo, downloaded locally so nothing breaks).
  hero: "assets/hero.jpg",

  // Signature picks shown in the "Fan Favorites" band.
  featured: [
    { name: "Carnivores", price: 15, image: "assets/beef.jpg", desc: "The loaded signature — patty, bacon, pepperoni, double cheese & KG sauce." },
    { name: "The Wing Vault", price: 10, image: "assets/wings.jpg", desc: "12 wings in all 12 flavors with 3 dips. Built for sharing." },
    { name: "Cowboy Butter Platter", price: 13, image: "assets/platter.jpg", desc: "Cowboy butter chicken, fries, cheesy garlic bread & caesar." },
    { name: "Iced Spanish Latte", price: 4, image: "assets/coffee.jpg", desc: "From The Noms — our coffee bar's most-ordered pour." },
  ],

  // Wing flavors showcase (Pick Your Flavors).
  wingFlavors: [
    { n: "BBQ" }, { n: "Hot Lemon", heat: 1 }, { n: "Honey Mustard" },
    { n: "Honey Garlic", heat: 1 }, { n: "Buffalo", heat: 3 }, { n: "Teriyaki" },
    { n: "Mango Habanero", heat: 2 }, { n: "Sweet Korean" }, { n: "Garlic Parmesan" },
    { n: "Spicy Hawaiian", heat: 1 }, { n: "Lemon Pepper" }, { n: "Gochujang", heat: 2 },
    { n: "Plain" }, { n: "Cheetos" }, { n: "Chipotle", heat: 1, limited: true },
  ],

  menu: [
    {
      id: "beef", name: "Beef Burgers", emoji: "🍔", image: "assets/beef.jpg",
      note: "Charcoal-grilled Australian Black Angus. Make any burger veggie — swap the patty for a plant-based one (red beans, mushrooms, onions).",
      items: [
        { id: "bf1", name: "Carnivores", price: 13.5, opt: "200g $15", emoji: "🍔", popular: true,
          desc: "Beef patty, hotdogs, beef bacon, pepperoni, chips, mozzarella, cheddar, honey mustard, BBQ & KG sauce in a brioche bun." },
        { id: "bf2", name: "Swiss Mushroom", price: 10.5, opt: "200g $12", emoji: "🍄",
          desc: "Black Angus patty, creamy mushroom sauce, mayo, Emmental, BBQ & caramelized onions in brioche." },
        { id: "bf3", name: "Classic OG", price: 9.5, opt: "200g $11", emoji: "🍔", popular: true,
          desc: "Black Angus patty, caramelized onions, KG sauce, cheddar, tomato, lettuce & dill pickles in brioche." },
        { id: "bf4", name: "Cheese Addict", price: 12.5, opt: "200g $14", emoji: "🧀",
          desc: "Black Angus patty, three cheeses, honey mustard, cheddar, lettuce & dill pickles in brioche." },
        { id: "bf5", name: "Pulled Beef", price: 15.5, emoji: "🍖", isNew: true,
          desc: "250g pulled beef, cheddar, chipotle BBQ, fried onions, pickles, coleslaw & garlic mayo on honey-glazed brioche, with a chipotle BBQ dip." },
        { id: "bf6", name: "Oklahoma", price: 12.5, emoji: "🧅",
          desc: "Triple smashed patties, thinly sliced onions, cheddar, dill pickles & KG sauce." },
        { id: "bf7", name: "Heisenberg", price: 12.5, opt: "200g", emoji: "🌶️", spicy: true,
          desc: "Black Angus patty, provolone, caramelized onions, jalapeños, hot honey ranch, honey mustard & rocca." },
        { id: "bf8", name: "Le Brie", price: 13.5, opt: "200g", emoji: "🫐",
          desc: "Black Angus patty, Brie, blueberry jam, caramelized onions, hot honey ranch, rocca & mayo." },
        { id: "bf9", name: "Jam Slam", price: 13, opt: "200g", emoji: "🌶️", spicy: true,
          desc: "Black Angus patty, beef-bacon jam, green chili, hot honey ranch, honey mustard & rocca." },
        { id: "bf10", name: "Old Money Beef", price: 12, emoji: "💵",
          desc: "200g Black Angus, cowboy sauce, pickles, cheddar, Emmental & raw onions on toasted brioche, served in a pan." },
        { id: "bf11", name: "Big Bro", price: 13.5, emoji: "🍔",
          desc: "Two Black Angus patties, beef bacon, caramelized onions, KG sauce, cheddar, dill pickles & lettuce on toasted brioche." },
        { id: "bf12", name: "The Don", price: 14, opt: "200g", emoji: "🧀",
          desc: "Black Angus patty, Emmental, jalapeños, cheese crisp, hot honey & mayo, served in a sizzling cheese pan." },
        { id: "bf13", name: "Pepper Jacked", price: 13.5, opt: "200g", emoji: "🫑", spicy: true,
          desc: "Black Angus patty stuffed with chili peppers & cream cheese, cheddar, fried onion, bacon & ranch." },
        { id: "bf14", name: "Flat Burger + Combo", price: 10.5, emoji: "🍔", popular: true,
          desc: "Smashed Black Angus patty, cheddar, chopped onions, sweet relish & flat sauce in a flat bun — served as a combo." },
        { id: "bf15", name: "KG Mini Box", price: 13.5, emoji: "🎁", isNew: true,
          desc: "Six mini burgers: Heisenberg, Jam Slam, Oklahoma, Classic OG, Thai Kid & Waffle-O." },
      ],
    },
    {
      id: "chicken", name: "Chicken Burgers", emoji: "🍗", image: "assets/chicken.jpg",
      note: "Upgrade any chicken burger to a combo for +$4 — adds fries, coleslaw, a soft drink & a dip.",
      items: [
        { id: "ch1", name: "Cajun Burger", price: 11.5, emoji: "🌶️", spicy: true,
          desc: "Crispy chicken, smoked chili cheese, Cajun sauce, lettuce & jalapeños in brioche." },
        { id: "ch2", name: "Crisp It", price: 11.5, emoji: "🧅",
          desc: "Crispy chicken, onion rings, cheddar patty, garlic mayo, honey mustard & cabbage in brioche." },
        { id: "ch3", name: "Cozy Burger", price: 8.5, emoji: "🍗", popular: true,
          desc: "Crispy chicken, garlic mayo, cheddar, lettuce, tomato & dill pickles in brioche." },
        { id: "ch4", name: "Waffle-O", price: 9.5, emoji: "🌶️", spicy: true,
          desc: "Nashville crispy chicken, takis, KG sauce & jalapeños in brioche." },
        { id: "ch5", name: "Loaded Bun", price: 10.5, emoji: "🍩", popular: true,
          desc: "Grilled chicken, Emmental, smoked special sauce, onions, garlic crisps, lettuce, roasted tomato & bacon on a glazed donut bun." },
        { id: "ch6", name: "Thai Kid", price: 8.5, emoji: "🌶️", spicy: true,
          desc: "Hot honey fried chicken, ranch, lettuce, dill pickles & secret sauce in brioche." },
        { id: "ch7", name: "Old Money Chicken", price: 8.5, emoji: "🍗",
          desc: "Grilled chicken, Emmental, herb-butter sauce, garlic mayo, lettuce & dill pickles in brioche." },
        { id: "ch8", name: "Twinflame Burgers", price: 9, emoji: "🔥",
          desc: "Two sliders — BBQ chicken + hot honey ranch, and Buffalo chicken + ranch — with dill pickles on Pain de Mie." },
        { id: "ch9", name: "Make It Veggie", price: 0, emoji: "🌱", veg: true,
          desc: "Swap any burger patty for a plant-based grilled patty (red beans, fresh mushrooms, onions)." },
      ],
    },
    {
      id: "wings", name: "Wings, Tenders & Combos", emoji: "🍗", image: "assets/wings.jpg",
      note: "Hand-breaded & tossed in any of our 15 flavors. Pick 2 flavors on wings, boneless & tenders. See all flavors below ↓",
      items: [
        { id: "wg1", name: "6 Wings + Dip", price: 5, opt: "Tossed +$1.5", emoji: "🍗",
          desc: "Six breaded wings in 2 flavors, with a dip." },
        { id: "wg2", name: "10 Wings + Dip", price: 6.5, opt: "Tossed +$1.5", emoji: "🍗", popular: true,
          desc: "Ten breaded wings in 2 flavors, with a dip." },
        { id: "wg3", name: "The Wing Vault", price: 10, emoji: "🗄️", isNew: true,
          desc: "12 wings in all 12 flavors, with 3 dips (Blue Cheese, Ranch, Hot Honey Ranch)." },
        { id: "wg4", name: "6 Boneless + Dip", price: 6.5, opt: "Tossed +$1.5", emoji: "🍗",
          desc: "Six boneless pieces in 2 flavors, with a dip." },
        { id: "wg5", name: "10 Boneless + Dip", price: 8, opt: "Tossed +$2", emoji: "🍗",
          desc: "Ten boneless pieces in 2 flavors, with a dip." },
        { id: "wg6", name: "3 Tenders + Dip", price: 6.5, opt: "Tossed +$1", emoji: "🍗",
          desc: "Three tenders (plain or hot) with a dip." },
        { id: "wg7", name: "5 Tenders + Dip", price: 8.5, opt: "Tossed +$1", emoji: "🍗",
          desc: "Five tenders (plain or hot) with a dip." },
        { id: "wg8", name: "Wing It", price: 16.5, emoji: "🪣",
          desc: "Group combo — 30 wings in 4 flavors, with fries & 2 dips." },
        { id: "wg9", name: "Handbreaded Chunks", price: 29, emoji: "🪣",
          desc: "Group combo — 30 boneless in 4 flavors, with fries & 2 dips." },
        { id: "wg10", name: "Master Combo", price: 28, emoji: "👑", popular: true,
          desc: "2 plain tenders, 10 wings, 10 boneless, 2 dips, loaded fries, wedges & 2 mozzarella sticks." },
        { id: "wg11", name: "Bits'n Buns", price: 35, emoji: "🎉",
          desc: "Classic OG burger, Crispy Chicken burger, 5 BBQ wings, 5 plain tenders, fries, curly fries, wedges, 2 mozzarella sticks, 2 onion rings, 7 dips & coleslaw." },
      ],
    },
    {
      id: "sandwiches", name: "Sandwiches & Steak Subs", emoji: "🥖", image: "assets/sandwich.jpg",
      items: [
        { id: "sw1", name: "Cheez Wiz Steak Sandwich", price: 12, opt: "280g", emoji: "🥩", popular: true,
          desc: "Chopped steak, provolone, caramelized onions & house-made cheez wiz in ciabatta." },
        { id: "sw2", name: "Truffle Steak Sandwich", price: 14, opt: "280g", emoji: "🍄",
          desc: "Chopped steak, provolone, caramelized onions, white truffle sauce, mushrooms & rocca in ciabatta." },
        { id: "sw3", name: "The Hulk", price: 12, opt: "280g", emoji: "💚",
          desc: "Chopped steak, herb-butter sauce, cheddar & chopped raw onions in ciabatta." },
        { id: "sw4", name: "Diesel 98", price: 8, emoji: "🥪",
          desc: "Grilled chicken, mozzarella, buffalo sauce, candied pepper, lettuce, tomato, onions & blue cheese sauce in ciabatta." },
        { id: "sw5", name: "Boneless Wrap", price: 6.5, emoji: "🌯",
          desc: "Boneless chicken in your choice of flavor — Honey Garlic, Buffalo, Mango Habanero, Garlic Parmesan, BBQ, Honey Mustard or Plain." },
      ],
    },
    {
      id: "sides", name: "Sides & Appetizers", emoji: "🍟", image: "assets/sides.jpg",
      items: [
        { id: "sd1", name: "Regular Fries", price: 4, emoji: "🍟" , desc: "Crispy golden fries." },
        { id: "sd2", name: "Large Fries", price: 5, emoji: "🍟", desc: "A bigger basket of golden fries." },
        { id: "sd3", name: "Curly Fries", price: 6.5, emoji: "🍟", desc: "Seasoned curly fries." },
        { id: "sd4", name: "Wedges", price: 4, emoji: "🥔", desc: "Chunky potato wedges." },
        { id: "sd5", name: "Truffle Fries", price: 6.5, emoji: "🍟", popular: true, desc: "Fries tossed in truffle & parmesan." },
        { id: "sd6", name: "Texas Fries", price: 9, emoji: "🍟", desc: "Fully loaded Texas-style fries." },
        { id: "sd7", name: "Animal-Style Fries", price: 6, emoji: "🍟", desc: "Cheese, sauce & grilled onions over fries." },
        { id: "sd8", name: "Nachville Fries", price: 7, opt: "Large $8", emoji: "🧀",
          desc: "Loaded fries — choose a flavor: Honey Mustard, BBQ, Buffalo, Cheddar or Ranch." },
        { id: "sd9", name: "Fried Pickles (10 pcs)", price: 3, emoji: "🥒", desc: "Crispy fried dill pickles." },
        { id: "sd10", name: "Mozzarella Sticks (5 pcs)", price: 5.5, emoji: "🧀", desc: "Golden mozzarella sticks with marinara." },
        { id: "sd11", name: "Ultimate Nachville Mozzarella Sticks", price: 6, emoji: "🧀",
          desc: "Two jumbo 120g sticks, served with ranch dip." },
        { id: "sd12", name: "Cheddar Jalapeño Bites (5 pcs)", price: 5.5, emoji: "🌶️", spicy: true, desc: "Crispy cheddar-jalapeño bites." },
        { id: "sd13", name: "KG Mix", price: 16, emoji: "🧺", popular: true,
          desc: "Fries, curly fries, wedges, crisscut, onion rings, hot-honey mozzarella bricks, cheddar balls, cheese balls & chili-cheese nuggets + 2 dips." },
      ],
    },
    {
      id: "salads", name: "Salads & Platters", emoji: "🥗", image: "assets/platter.jpg",
      items: [
        { id: "sl1", name: "Green Salad", price: 5.5, emoji: "🥗", veg: true,
          desc: "Mixed greens, cherry tomato & lemon-mustard dressing." },
        { id: "sl2", name: "Chicken Caesar Salad", price: 6.5, emoji: "🥗",
          desc: "Grilled chicken, lettuce, caesar dressing, parmesan & herb croutons." },
        { id: "sl3", name: "Grilled Chicken Platter", price: 11, emoji: "🍽️",
          desc: "Grilled chicken with fries, cheesy garlic bread, caesar salad & dipping sauce." },
        { id: "sl4", name: "Cowboy Butter Chicken Platter", price: 13, emoji: "🍽️", popular: true,
          desc: "Cowboy butter chicken with fries, cheesy garlic bread, caesar salad & dipping sauce." },
        { id: "sl5", name: "Creamy Mushroom Chicken Platter", price: 13, emoji: "🍄",
          desc: "Creamy mushroom chicken with fries, cheesy garlic bread, caesar salad & dipping sauce." },
      ],
    },
    {
      id: "noms", name: "The Noms · Coffee", emoji: "☕", image: "assets/coffee.jpg",
      note: "Our in-house coffee bar. Espresso, signature lattes & more — hot or iced.",
      items: [
        { id: "nm1", name: "Single Espresso", price: 2, emoji: "☕", desc: "A clean single shot." },
        { id: "nm2", name: "Double Espresso", price: 2.5, emoji: "☕", desc: "Double the shot." },
        { id: "nm3", name: "Americano", price: 2.5, emoji: "☕", opt: "Iced $2.5", desc: "Espresso & hot water." },
        { id: "nm4", name: "Cappuccino", price: 3.5, emoji: "☕", desc: "Espresso, steamed milk & foam." },
        { id: "nm5", name: "Latte", price: 3.5, emoji: "☕", opt: "Iced $3.5", desc: "Espresso & silky steamed milk." },
        { id: "nm6", name: "Mocha", price: 4.5, emoji: "☕", opt: "Iced $4.5", desc: "Espresso, chocolate & milk." },
        { id: "nm7", name: "Spanish Latte", price: 4, emoji: "🥛", opt: "Iced $4", popular: true, desc: "Espresso with sweetened condensed milk." },
        { id: "nm8", name: "Hot Chocolate", price: 4.5, emoji: "🍫", desc: "Rich melted chocolate & milk." },
        { id: "nm9", name: "Chai Latte", price: 5, emoji: "🍵", desc: "Spiced chai with steamed milk." },
        { id: "nm10", name: "Matcha Latte", price: 6.5, emoji: "🍵", desc: "Ceremonial matcha & milk." },
        { id: "nm11", name: "Ube Matcha Latte", price: 7.5, emoji: "💜", desc: "Ube & matcha with milk." },
        { id: "nm12", name: "Crème Brûlée Latte", price: 5, emoji: "🍮", opt: "Hot / Iced", desc: "Caramelized crème brûlée latte." },
        { id: "nm13", name: "Hot Tiramisu Latte", price: 6, emoji: "☕", desc: "Tiramisu-spiced latte." },
        { id: "nm14", name: "Iced Lotus Biscoff Latte", price: 5, emoji: "🍪", desc: "Iced latte with Lotus Biscoff." },
        { id: "nm15", name: "Iced Vanilla Matcha Latte", price: 6.5, emoji: "🍵", desc: "Vanilla & matcha over ice." },
        { id: "nm16", name: "Iced Matcha Strawberry Latte", price: 7.5, emoji: "🍓", desc: "Matcha & strawberry over ice." },
        { id: "nm17", name: "Ube Cloud Latte", price: 7.5, emoji: "☁️", desc: "Dreamy ube cloud latte." },
        { id: "nm18", name: "Caramelized Affogato", price: 5, emoji: "🍨", desc: "Espresso over ice cream, caramelized." },
      ],
    },
    {
      id: "shakes", name: "Shakes, Lemonades & Teas", emoji: "🥤", image: "assets/shakes.jpg",
      items: [
        { id: "shk1", name: "Cookies N Cream Shake", price: 5.5, emoji: "🥤", popular: true, desc: "Thick cookies-and-cream milkshake." },
        { id: "shk2", name: "Strawberry Shortcake Shake", price: 5.5, emoji: "🍓", desc: "Strawberry shortcake milkshake." },
        { id: "shk3", name: "Banoffee Shake", price: 6, emoji: "🍌", desc: "Banana & toffee milkshake." },
        { id: "shk4", name: "Classic Lemonade", price: 3, emoji: "🍋", veg: true, desc: "Fresh-squeezed lemonade." },
        { id: "shk5", name: "Minted Lemonade", price: 3.5, emoji: "🌿", veg: true, desc: "Lemonade with fresh mint." },
        { id: "shk6", name: "Strawberry Lemonade", price: 4, emoji: "🍓", veg: true, desc: "Strawberry lemonade." },
        { id: "shk7", name: "Raspberry Matcha Lemonade", price: 7, emoji: "🍵", desc: "Raspberry & matcha lemonade." },
        { id: "shk8", name: "Pot of Tea", price: 3, emoji: "🍵",
          desc: "Choose: English, Ginger, Chamomile, Blue Flower Earl, Jasmine or Marakish." },
      ],
    },
    {
      id: "desserts", name: "Desserts", emoji: "🍰", image: "assets/dessert.jpg",
      note: "Weekly rotating specials — ask your server what's fresh.",
      items: [
        { id: "ds1", name: "Cookie Comb", price: 8, emoji: "🍪", popular: true,
          desc: "Cookie dough filled with pistachio spread & chocolate ganache, topped with Belgian chocolate, crunchy flakes & vanilla ice cream." },
        { id: "ds2", name: "Tiramisu Brownies", price: 7, emoji: "🍫",
          desc: "Rich brownie layered with tiramisu & smooth chocolate ganache." },
        { id: "ds3", name: "Pain Perdu", price: 7, emoji: "🍞",
          desc: "Thick brioche soaked in vanilla, toasted & topped with caramel sauce & ice cream." },
      ],
    },
    {
      id: "drinks", name: "Drinks & Dips", emoji: "🥫", image: "assets/dips.jpg",
      items: [
        { id: "dr1", name: "Ice Tea", price: 2, emoji: "🧋", desc: "Chilled iced tea." },
        { id: "dr2", name: "Soft Drinks", price: 1.5, emoji: "🥤", desc: "Coke, Sprite, Fanta & more." },
        { id: "dr3", name: "Sparkling Water", price: 1.5, emoji: "💧", desc: "Chilled sparkling water." },
        { id: "dr4", name: "Still Water", price: 0.5, emoji: "💧", desc: "Bottled still water." },
        { id: "dr5", name: "Dipping Wheel", price: 6, emoji: "🛞", popular: true, desc: "Eight dipping sauces on one wheel." },
        { id: "dr6", name: "Ranch Dip", price: 1, emoji: "🥫", desc: "House ranch." },
        { id: "dr7", name: "Hot Honey Ranch Dip", price: 1, emoji: "🍯", desc: "Sweet-heat ranch." },
        { id: "dr8", name: "KG Sauce Dip", price: 1, emoji: "🥫", desc: "Our signature KG sauce." },
        { id: "dr9", name: "Chic-Fil-A Dip", price: 1.5, emoji: "🥫", desc: "Tangy signature-style dip." },
        { id: "dr10", name: "Cheddar Dip", price: 1.5, emoji: "🧀", desc: "Warm cheddar dip." },
        { id: "dr11", name: "Blue Cheese Dip", price: 1.5, emoji: "🧀", desc: "Creamy blue cheese." },
      ],
    },
  ],

  payments: [
    { id: "cod",      label: "Cash on Delivery",     emoji: "💵", on: true, note: "Pay the rider in cash" },
    { id: "card",     label: "Credit / Debit Card",  emoji: "💳", on: true, note: "Visa, Mastercard, Amex" },
    { id: "applepay", label: "Apple Pay",            emoji: "🍏", on: true, note: "Fast & secure" },
    { id: "googlepay",label: "Google Pay",           emoji: "🔵", on: true, note: "Fast & secure" },
    { id: "whish",    label: "Whish Money",          emoji: "📲", on: true, note: "Pay from your Whish wallet" },
    { id: "crypto",   label: "Crypto",               emoji: "₿",  on: true, note: "BTC, USDT & more — we accept crypto" },
    { id: "omt",      label: "OMT / Bank Transfer",  emoji: "🏦", on: true, note: "We'll send transfer details" },
  ],
};
